import json
import requests
from headers import headers_price_update


def Update_Price(session: requests.Session, params):
    """_summary_

    Args:
        session (requests.Session): _description_
    """
    raw_data = {
        "HotelPriceId": params["HotelPriceId"],
        "HotelId": params["HotelId"],
        "Status": "1",
        "HotelPrice": {
            "HotelId": params["HotelId"],
            "HotelRateTypeId": "2",
            "IsIncludeBreakfast": "True",
            "IsIncludeKDV": "True",
            "IsGroupRate": "False",
            "Remark": "",
            "UserId": "",
            "MarketId": "1",
            "IsActionRate": "False",
            "IsOpportunity": "False",
            "IsSpecialPeriod": "False",
            "IsPackageRate": "False",
            "EarlyBooking": "False",
            "AlternativePrice": "False",
            "HotelPriceRateTypeId": "1",
            "HotelPriceComissionList": [
                {"MarkupCommissionTypeId": "1", "Commission": "15,00", "ComissionAmountTypeId": "1"},
                {"MarkupCommissionTypeId": "2", "Commission": "", "ComissionAmountTypeId": "1"},
            ],
            "KDVAmountType": "",
            "KDVRate": "",
            "PriceTitle": params["PriceTitle"],
            "MinNight": params["MinNight"],
            "MealTypeId": params["pension type"],
            "CurrencySale": "",
            "Currency": params["Currency"],
            "ScopePath": params["ScopePath"],
            "HotelCancelPolicyId": params["HotelCancelPolicyId"],
            "ExcludeScopePaths": params["ExcludeScopePaths"],
            "IsSingleMaleRestriction": params["IsSingleMaleRestriction"],
            "Id": params["HotelPriceId"],
            "StartDate": params["CheckinStartDate"],
            "EndDate": params["CheckinEndDate"],
            "HotelPriceItemGroupedList": [
                {
                    "IsDisable": "true",
                    "HotelRoomId": params["HotelRoomId"],
                    "HotelRoomTypeName": params["HotelRoomTypeName"],
                    "HotelPriceItemList": [
                        {
                            "HotelRoomId": params["HotelRoomId"],
                            "HotelId": params["HotelId"],
                            "HotelPriceId": params["HotelPriceId"],
                            "HotelAccommodationOptionTypeValue": "1",
                            "ChildRanges": {
                                "1Cocuk": [
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "223856352",
                                        "ChildPriceGroupTypeId": "1",
                                        "ChildTypeId": "1",
                                        "AgeFrom": "0,00",
                                        "AgeTo": "6,99",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "2",
                                        "ChildTypeId": "1",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "3",
                                        "ChildTypeId": "1",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                ],
                                "2Cocuk": [
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "1",
                                        "ChildTypeId": "2",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "2",
                                        "ChildTypeId": "2",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "3",
                                        "ChildTypeId": "2",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                ],
                                "3Cocuk": [
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "1",
                                        "ChildTypeId": "3",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "2",
                                        "ChildTypeId": "3",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "3",
                                        "ChildTypeId": "3",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                ],
                                "4Cocuk": [
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "1",
                                        "ChildTypeId": "4",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "2",
                                        "ChildTypeId": "4",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "3",
                                        "ChildTypeId": "4",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                ],
                            },
                            "RateCost": params["Double"]["RateCost"],
                            "RateSale": "",
                            "ExtraBedCost": params["Double"]["ExtraBedCost"],
                            "ExtraBedSale": "",
                            "IsExtrabedDisable": True if params["Double"]["ExtraBedCost"] == "" else False,
                            "Child1Cost": params["Double"]["Child1Cost"],  # "450,00",
                            "Child1Cost2": "",
                            "Child1Sale": "",
                            "Child1Sale2": "",
                            "Child2Cost": params["Double"]["Child2Cost"],  # "450,00",
                            "Child2Cost2": "",
                            "Child2Sale": "",
                            "Child2Sale2": "",
                            "Child3Cost": params["Double"]["Child3Cost"],  # "450,00",
                            "Child3Cost2": "",
                            "Child3Sale": "",
                            "Child3Sale2": "",
                            "Child4Cost": params["Double"]["Child4Cost"],  # "450,00",
                            "Child4Cost2": "",
                            "Child4Sale": "",
                            "Child4Sale2": "",
                            "IsChild1Disable": True if params["Double"]["Child1Cost"] == "" else False,
                            "IsChild2Disable": True if params["Double"]["Child2Cost"] == "" else False,
                            "IsChild3Disable": True if params["Double"]["Child3Cost"] == "" else False,
                            "IsChild4Disable": True if params["Double"]["Child4Cost"] == "" else False,
                        },
                        {
                            "HotelRoomId": params["HotelRoomId"],
                            "HotelId": params["HotelId"],
                            "HotelPriceId": params["HotelPriceId"],
                            "HotelAccommodationOptionTypeValue": "2",
                            "ChildRanges": {
                                "1Cocuk": [
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "223856367",
                                        "ChildPriceGroupTypeId": "1",
                                        "ChildTypeId": "1",
                                        "AgeFrom": "0,00",
                                        "AgeTo": "6,99",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "2",
                                        "ChildTypeId": "1",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "3",
                                        "ChildTypeId": "1",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                ],
                                "2Cocuk": [
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "1",
                                        "ChildTypeId": "2",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "2",
                                        "ChildTypeId": "2",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "3",
                                        "ChildTypeId": "2",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                ],
                                "3Cocuk": [
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "1",
                                        "ChildTypeId": "3",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "2",
                                        "ChildTypeId": "3",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "3",
                                        "ChildTypeId": "3",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                ],
                                "4Cocuk": [
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "1",
                                        "ChildTypeId": "4",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "2",
                                        "ChildTypeId": "4",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "3",
                                        "ChildTypeId": "4",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                ],
                            },
                            "RateCost": params["Single"]["RateCost"],  # "1800,00",
                            "RateSale": "",
                            "ExtraBedCost": params["Single"]["ExtraBedCost"],
                            "ExtraBedSale": "",
                            "IsExtrabedDisable": True if params["Double"]["ExtraBedCost"] == "" else False,  # "true",
                            "Child1Cost": params["Single"]["Child1Cost"],  # "450,00",
                            "Child1Cost2": "",
                            "Child1Sale": "",
                            "Child1Sale2": "",
                            "Child2Cost": params["Single"]["Child2Cost"],  # "450,00",
                            "Child2Cost2": "",
                            "Child2Sale": "",
                            "Child2Sale2": "",
                            "Child3Cost": params["Single"]["Child3Cost"],  # "450,00",
                            "Child3Cost2": "",
                            "Child3Sale": "",
                            "Child3Sale2": "",
                            "Child4Cost": params["Single"]["Child4Cost"],  # "450,00",
                            "Child4Cost2": "",
                            "Child4Sale": "",
                            "Child4Sale2": "",
                            "IsChild1Disable": True if params["Single"]["Child1Cost"] == "" else False,
                            "IsChild2Disable": True if params["Single"]["Child2Cost"] == "" else False,
                            "IsChild3Disable": True if params["Single"]["Child3Cost"] == "" else False,
                            "IsChild4Disable": True if params["Single"]["Child4Cost"] == "" else False,
                        },
                        {
                            "HotelRoomId": params["HotelRoomId"],
                            "HotelId": params["HotelId"],
                            "HotelPriceId": params["HotelPriceId"],
                            "HotelAccommodationOptionTypeValue": "3",
                            "ChildRanges": {
                                "1Cocuk": [
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "223856379",
                                        "ChildPriceGroupTypeId": "1",
                                        "ChildTypeId": "1",
                                        "AgeFrom": "0,00",
                                        "AgeTo": "6,99",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "2",
                                        "ChildTypeId": "1",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "3",
                                        "ChildTypeId": "1",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                ],
                                "2Cocuk": [
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "1",
                                        "ChildTypeId": "2",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "2",
                                        "ChildTypeId": "2",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "3",
                                        "ChildTypeId": "2",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                ],
                                "3Cocuk": [
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "1",
                                        "ChildTypeId": "3",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "2",
                                        "ChildTypeId": "3",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "3",
                                        "ChildTypeId": "3",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                ],
                                "4Cocuk": [
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "1",
                                        "ChildTypeId": "4",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "2",
                                        "ChildTypeId": "4",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                    {
                                        "Id": "0",
                                        "HotelChildRangeTemplateRelationId": "0",
                                        "ChildPriceGroupTypeId": "3",
                                        "ChildTypeId": "4",
                                        "AgeFrom": "",
                                        "AgeTo": "",
                                    },
                                ],
                            },
                            "RateCost": params["Triple"]["RateCost"],  # "2430,00",
                            "RateSale": "",
                            "ExtraBedCost": params["Double"]["ExtraBedCost"],
                            "ExtraBedSale": "",
                            "IsExtrabedDisable": True if params["Double"]["ExtraBedCost"] == "" else False,  # "true",
                            "Child1Cost": params["Triple"]["Child1Cost"],  # "450,00",
                            "Child1Cost2": "",
                            "Child1Sale": "",
                            "Child1Sale2": "",
                            "Child2Cost": params["Triple"]["Child2Cost"],  # "450,00",
                            "Child2Cost2": "",
                            "Child2Sale": "",
                            "Child2Sale2": "",
                            "Child3Cost": params["Triple"]["Child3Cost"],  # "450,00",
                            "Child3Cost2": "",
                            "Child3Sale": "",
                            "Child3Sale2": "",
                            "Child4Cost": params["Triple"]["Child4Cost"],  # "450,00",
                            "Child4Cost2": "",
                            "Child4Sale": "",
                            "Child4Sale2": "",
                            "IsChild1Disable": True if params["Triple"]["Child1Cost"] == "" else False,
                            "IsChild2Disable": True if params["Triple"]["Child2Cost"] == "" else False,
                            "IsChild3Disable": True if params["Triple"]["Child3Cost"] == "" else False,
                            "IsChild4Disable": True if params["Triple"]["Child4Cost"] == "" else False,
                        },
                    ],
                }
            ],
        },
    }

    payload = json.dumps(raw_data)

    response = session.post(
        "https://extranet.jollytur.ws/HotelPrice/SaveHotelPrice",
        headers=headers_price_update,
        data=payload,
    )

    print(response.text)
